version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025" # SMTP порт
      - "8025:8025" # Веб-интерфейс MailHog

  app:
    build: .
    depends_on:
      - db
      - mailhog
    # Не публикуем порты напрямую, nginx будет проксировать
    # ports:
    #  - "8080:8080"
    environment:
      # Обновленные настройки SMTP для использования MailHog
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      # SMTP_USER и SMTP_PASS больше не нужны для MailHog
    volumes:
      - ./uploads:/app/uploads

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    ports:
      - "80:80" # Публичный порт для доступа к приложению
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/app/uploads:ro # Монтируем uploads только для чтения

volumes:
  pgdata:
